import type { FILM_LIST_ITEM } from '@shared/types/Film'
import { FILM_CATEGORY } from '@shared/enums/FilmCategory'

export const FILMS: readonly FILM_LIST_ITEM[] = [
  {
    id:          'f1',
    title:       'Into the Light',
    slug:        'into-the-light',
    category:    FILM_CATEGORY.WEDDING,
    posterImage: { id: 'f1-poster', src: '', alt: 'Into the Light — Wedding Film', width: 1920, height: 1080 },
    videoUrl:    '',
    duration:    '08:42',
    isFeatured:  true,
    tagline:     'A love story told through golden hour.',
  },
  {
    id:          'f2',
    title:       'City of Silence',
    slug:        'city-of-silence',
    category:    FILM_CATEGORY.DOCUMENTARY,
    posterImage: { id: 'f2-poster', src: '', alt: 'City of Silence — Documentary', width: 1920, height: 1080 },
    videoUrl:    '',
    duration:    '14:30',
    isFeatured:  false,
    tagline:     'The streets speak when no one is listening.',
  },
  {
    id:          'f3',
    title:       'Bloom',
    slug:        'bloom',
    category:    FILM_CATEGORY.COMMERCIAL,
    posterImage: { id: 'f3-poster', src: '', alt: 'Bloom — Commercial', width: 1920, height: 1080 },
    videoUrl:    '',
    duration:    '02:15',
    isFeatured:  true,
    tagline:     'Nature. Refined.',
  },
  {
    id:          'f4',
    title:       'Before Dawn',
    slug:        'before-dawn',
    category:    FILM_CATEGORY.SHORT_FILM,
    posterImage: { id: 'f4-poster', src: '', alt: 'Before Dawn — Short Film', width: 1920, height: 1080 },
    videoUrl:    '',
    duration:    '06:55',
    isFeatured:  false,
    tagline:     'Some moments only exist in the threshold.',
  },
  {
    id:          'f5',
    title:       'Resonance',
    slug:        'resonance',
    category:    FILM_CATEGORY.BRAND,
    posterImage: { id: 'f5-poster', src: '', alt: 'Resonance — Brand Film', width: 1920, height: 1080 },
    videoUrl:    '',
    duration:    '03:40',
    isFeatured:  false,
    tagline:     'Sound and vision, unified.',
  },
  {
    id:          'f6',
    title:       'Ceremony',
    slug:        'ceremony',
    category:    FILM_CATEGORY.EVENT,
    posterImage: { id: 'f6-poster', src: '', alt: 'Ceremony — Event Film', width: 1920, height: 1080 },
    videoUrl:    '',
    duration:    '05:20',
    isFeatured:  false,
    tagline:     'Every gathering has a soul.',
  },
]
